### ISSUE TITLE
remove `expect`/`then` label

### ISSUE THREAD

**Issue by jeysal** [spockjs/spockjs#47]
The labels are still present after following the codemod escape route (#39), which is annoying.
To be decided: Do we
* always remove them,
* remove them by default with an option to keep them, or
* remove them only if an option is set?

**Comment by succcubbus** [comment]
Always remove them unless they are referenced.
In that case, it would be fine for the plugin to fail.

**Comment by jeysal** [comment]
Referencing cannot actually happen; you would either already get "Expected an ExpressionStatement" or "Unsyntactic break".
I cannot think of any case where code that references an `expect` label gets through both the parser and the ExpressionStatement check
